sre-provisioning:
  base:
    environment: stable
    imageRepository: 558830342743.dkr.ecr.us-east-1.amazonaws.com
    namespace: checkout-ui-tests-stable
    repoName: checkout-ui-tests
    repoOrg: vtex
    secretsManager:
      enabled: true
      secretsName: stable/checkout-ui-tests/checkout-ui-tests
    version: 0.19.10
  apps:
  - activeDeadlineSeconds: 2400
    command:
    - yarn
    - test
    dockerfile: ./dockerfiles/stable/Dockerfile
    envs:
    - name: VTEX_ENV
      value: stable
    - name: HORUS_PROXY_KEY
      valueFrom:
        secretKeyRef:
          key: HORUS_PROXY_KEY
          name: checkout-ui-tests
          optional: false
    - name: HORUS_COGNITO_CREDENTIALS
      valueFrom:
        secretKeyRef:
          key: HORUS_COGNITO_CREDENTIALS
          name: checkout-ui-tests
          optional: false
    - name: CYPRESS_APP_KEY
      valueFrom:
        secretKeyRef:
          key: APP_KEY
          name: checkout-ui-tests
          optional: false
    - name: CYPRESS_APP_TOKEN
      valueFrom:
        secretKeyRef:
          key: APP_TOKEN
          name: checkout-ui-tests
          optional: false
    - name: CYPRESS_RECORD_KEY
      valueFrom:
        secretKeyRef:
          key: RECORD_KEY
          name: checkout-ui-tests
          optional: false
    imagePullPolicy: Always
    imageRepoName: healthcheck/webtests/checkout
    kind: cronjob
    name: checkout-tests-cronjob
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 2
        memory: 2Gi
    schedule: '* * * * *'
    serviceAccount:
      arn: arn:aws:iam::558830342743:role/s3-healthcheck-io
    startingDeadlineSeconds: 6000
    volumes:
    - mountPath: /dev/shm
      name: dshm
