- acronym: checkout-ui-tests
  description: Deploy checkout-ui-tests with DK CICD
  name: checkout-ui-tests
  build:
    provider: dkcicd
    pipelines:
    - name: application-build-v1
      parameters:
        acronym: checkout-ui-tests
        applicationName: checkout-ui-tests
        applicationType: k8s
        dockerfilePath: ./Dockerfile
        environmentType: stable
        imageRepo: vtex/checkout-ui-tests
        imageTag: '{{ ref_name }}'
        rollout: "true"
        chartName: sre-provisioning
        baseBranch: main
      when:
        - event: push
          source: tag
          regex: (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(\.(0|[1-9]\d*))?$
      runtime:
        architecture: amd64

    - name: application-deploy-v2
      parameters:
        acronym: checkout-ui-tests
        projectName: sre-apps
        baseBranch: main
      when:
        - event: push
          source: branch
          regex: ^(main)$
      runtime:
        architecture: amd64
