kind: pipeline
type: kubernetes
name: Deployment Stable
steps:
  - name: docker-build
    image: docker
    pull: if-not-exists
    environment:
      DOCKER_REGISTRY: 558830342743.dkr.ecr.us-east-1.amazonaws.com
    commands:
      - >-
        docker build --network=host -t
        $$DOCKER_REGISTRY/healthcheck/webtests/checkout:latest -f
        ./dockerfiles/stable/Dockerfile .
    volumes:
      - name: dockersock
        path: /var/run
trigger:
  event:
    - push
    - tag
volumes:
  - name: dockersock
    host:
      path: /var/run/
