name: ESLint

on:
  push:
    paths-ignore:
      - 'Dockerfile'
      - '.vtex/**'
  pull_request:
    paths-ignore:
      - 'Dockerfile'
      - '.vtex/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run Lint
        run: |
          yarn
          yarn lint
        env:
          CI: true
